### ISSUE TITLE
[CIS Azure] Implement identity provider

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1280]
**Motivation**
We would like to have an identity provider, this is needed order to understand the scope of the credentials and what resources we are working on.
Sending this additional information to the index and populating the findings will give the user an additional layer of understanding.

Since we query the resources via subscription/s id/s and management group/s id/s and this information is not provided be default.

We either need to pull it with the help of an identity provider or assign it as part of the integration (user filled values that are being passed via agent configuration).

**Definition of done**
What needs to be completed at the end of this task
- [ ] Implement the provider and make sure that we have all of the needed identity information for population
- [ ] Utilize this provider to get the subscriptions, management groups as well

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by jeniawhite** [comment]
Due to 8.11 time constraints, we've implemented partial needed features regarding identity:
- https://github.com/elastic/cloudbeat/pull/1396
- https://github.com/elastic/cloudbeat/pull/1394
- https://github.com/elastic/cloudbeat/pull/1366
This ticket needs to be re-evaluated for 8.12 release with the appropriate changes that are relevant for organizations.

**Comment by orestisfl** [comment]
We now have a provider for subs and mgs, should be complete after https://github.com/elastic/cloudbeat/pull/1559

Please re-open if something is still missing.

**Comment by kfirpeled** [comment]
To verify this issue, follow the [PRs](https://github.com/elastic/cloudbeat/issues/1280#issuecomment-1763473944) mentioned above - self explanatory

Feel free to contact anyone on slack/here if you have questions
