### ISSUE TITLE
[BUG] Filtering cloudbeat logs on Agent Logs page yields no results

### ISSUE THREAD

**Issue by yashtewari** [elastic/cloudbeat#170]
**Describe the bug**
Filtering cloudbeat logs doesn’t seem to work as it should. All the logs can be viewed when the search phrase is empty or when the search phase is `*`. But for any more specific search phase, no results are yielded.

**Preconditions**
Setup the environment with CIS integration added to an Agent policy that is running on an Agent deployed on Kubernetes. The CIS integration should trigger cloudbeat to run on the Agent, so cloudbeat logs should start appearing on the Agent logs page.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Bring up the stack
```
elastic-package stack down -v
elastic-package stack update -v
elastic-package stack up --version 8.3.0-SNAPSHOT -v -d
```
2. Open Kibana, create a new Agent policy and add the CIS integration to it
3. Follow the instructions to deploy the Agent on your Kubernetes cluster
4. Wait for the Agent to appear on the Fleet page on Kibana, and open the Logs page
5. Select only "cloudbeat" from the drop down, and try to filter the logs

**Expected behavior**

The logs should get filtered according to the given search phrase.

**Screenshots**

![image](https://user-images.githubusercontent.com/9020112/169987227-44ea0ae4-07d4-413c-a616-7225d5b8c094.png)
![image](https://user-images.githubusercontent.com/9020112/169987250-4fb2ae24-144c-48c5-894c-491025c78414.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Kibana version: `753fd99d64d52a5bf836a05a4c3f077406720406`
 - Cloudbeat version: `90351179dc206fefbceb104df53f2af62a77bbd5`
 - Integration package `cloud_security_posture` version: `0.10.0`
 - Integration package `elastic_agent` version: `1.3.3`

**Additional context**

Earlier related bug and associated PRs: https://github.com/elastic/cloudbeat/issues/120

**Comment by yashtewari** [comment]
Confirmed that this is an issue only for cloudbeat. Have an inkling that it should be solved with more configuration fixes in the integrations package.

**Comment by tehilashn** [comment]
pushing that to 8.4 as we have a workaround

**Comment by oren-zohar** [comment]
Fixed:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/85433724/181518754-aa79db69-8205-419a-bc6f-b80715545557.png">

**Comment by CohenIdo** [comment]
Verification passed using Kibana Commit sha: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d

**Comment by yashtewari** [comment]
@oren-zohar @CohenIdo are we really sure that's fixed?

@oren-zohar the screenshot you posted only selects the cloudbeat logs, which was [fixed here](https://github.com/elastic/cloudbeat/issues/120). To recreate, you have to then type something in the search bar to filter the cloudbeat logs, as shown in my second screenshot above.

**Comment by CohenIdo** [comment]
Hey @yashtewari thanks, you right, the filtering is still not working. I reopened the issue

https://user-images.githubusercontent.com/90558359/182106817-14c91a98-bd5a-4ed4-8a0d-692e602c63ef.mov

**Comment by oren-zohar** [comment]
oh I see, I thought it was just filtering not searching

**Comment by oren-zohar** [comment]
Update: 
Seems like this is happning since our package `component_templates` is missing two fields from the query fields: the `message` and the `log.level`.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/85433724/182149636-7325abce-45d5-4e18-85a8-381d79db4914.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/85433724/182149644-fc3c7e92-8ad1-4a25-bdb3-d03a45d82abb.png">

**Comment by oren-zohar** [comment]
Related: - https://github.com/elastic/kibana/issues/137703

**Comment by joshdover** [comment]
FYI you can work around this by searching on `message:"your search"` explicitly

**Comment by yashtewari** [comment]
> For now, I will set the message field explicitly as they do in [filebeat](https://github.com/elastic/integrations/blob/cc68f3efc0f26d9fdbcf570dd03eac089f9f1e75/packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml#L1-L3)

Does that work on your local setup @oren-zohar? Wondering how it relates to [this comment](https://github.com/elastic/integrations/pull/3378#discussion_r876134782)

**Comment by yashtewari** [comment]
I'm assuming that's the auto-close from the PR. @oren-zohar did you manage to test that it works?

**Comment by oren-zohar** [comment]
@yashtewari Seems like it didn't fix it, re-opening 
![image](https://user-images.githubusercontent.com/85433724/184528493-488cf8d0-4c12-4855-8903-9812916553be.png)

**Comment by amirbenun** [comment]
Moving to 8.5

**Comment by oren-zohar** [comment]
Closing as this issue is fixed in elastic agent `1.3.5`:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/85433724/187180221-f4ba0e67-4242-4512-a488-fb2ca60d3462.png">

@joshdover

**Comment by yashtewari** [comment]
Does it still require this type of query though? Ideally a user should just be able to type the string `Connection` into the search bar and get this log as part of the results.

**Comment by oren-zohar** [comment]
> Question: does it still require this type of query though? Ideally a user should just be able to type the string `Connection` into the search bar and get this log as part of the results.

this type of query is not required when searching in the fleet logs window, i.e. just searching `Connection` works
